/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CroBindings */

#ifndef _Included_CroBindings
#define _Included_CroBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CroBindings
 * Method:    jsonrpc
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CroBindings_jsonrpc
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
