---
kind: pipeline
name: default

steps:
- name: test
  image: chain
  pull: never
  commands:
  - export RUST_BACKTRACE=1
  - export RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
  - export LD_LIBRARY_PATH=$HOME/lib
  - export LIBRARY_PATH=$HOME/lib
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig
  - cargo build
  - cargo test
  - echo "HOME FOLDER = " $HOME

---

kind: pipeline
type: exec
name: sgx-cargo-1804-hw1

platform:
  os: linux
  arch: amd64

steps:
- name: hw-test-tx-validation
  commands:
  - export SGX_MODE=HW
  - export NETWORK_ID=ab
  - . /opt/intel/sgxsdk/sgxsdk/environment
  - rustup default nightly-2019-08-01-x86_64-unknown-linux-gnu
  - ls -l /dev/sgx
  - ls -l /var/run/aesmd/aesm.socket
  - cd chain-tx-enclave/tx-validation && make clean && SGX_TEST=1 make
  - cd bin && ./tx-validation-app

trigger:
  branch:
  - master
  - staging
  - trying
  event:
  - push

---

kind: pipeline
type: exec
name: sgx-cargo-1804-hw2

platform:
  os: linux
  arch: amd64

steps:
- name: hw-test-tx-query
  environment:
    SPID:
      from_secret: dev_spid
    IAS_API_KEY:
      from_secret: dev_ias_key
  commands:
  - export RUST_BACKTRACE=1
  - export RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
  - export SGX_MODE=HW
  - export NETWORK_ID=ab
  - export RUST_LOG=info
  - export TX_VALIDATION_BIN_DIR=`pwd`/chain-tx-enclave/tx-validation/bin/
  - . /opt/intel/sgxsdk/sgxsdk/environment
  - rustup default nightly-2019-08-01-x86_64-unknown-linux-gnu
  - ls -l /dev/sgx
  - ls -l /var/run/aesmd/aesm.socket
  - cd chain-tx-enclave/tx-validation && make clean && make
  - cd ../tx-query && make clean && SGX_TEST=1 make
  - cd bin && ./tx-query-app
  
trigger:
  branch:
  - master
  - staging
  - trying
  event:
  - push
---
kind: signature
hmac: bdc2684e182cf00ebf7a8a2e7971884e5ff9ee193d16398aec745bcd1260cf6f

...
