---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export PATH=$CARGO_HOME/bin:$PATH
  - export CERTIFICATE_EXPIRATION_SECS=200
  - ./docker/build.sh

- name: unit-tests
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export CRYPTO_CHAIN_ENABLE_SANITY_CHECKS=1
  - cargo test

- name: integration-tests
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  privileged: true
  volumes:
  - name: sgx
    path: /dev/sgx
  environment:
    SPID:
      from_secret: SPID
    IAS_API_KEY:
      from_secret: IAS_API_KEY
  commands:
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export PATH=$CARGO_HOME/bin:$PATH
  - export PYTHON_VENV_DIR=$PWD/drone/venv
  - export CRYPTO_CHAIN_ENABLE_SANITY_CHECKS=1
  - LD_LIBRARY_PATH=/opt/intel/sgx-aesm-service/aesm /opt/intel/sgx-aesm-service/aesm/aesm_service --no-daemon &
  - ./integration-tests/run.sh

- name: multinode-tests
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  privileged: true
  volumes:
  - name: sgx
    path: /dev/sgx
  environment:
    SPID:
      from_secret: SPID
    IAS_API_KEY:
      from_secret: IAS_API_KEY
  commands:
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export PATH=$CARGO_HOME/bin:$PATH
  - export PYTHON_VENV_DIR=$PWD/drone/venv
  - export CRYPTO_CHAIN_ENABLE_SANITY_CHECKS=1
  - LD_LIBRARY_PATH=/opt/intel/sgx-aesm-service/aesm /opt/intel/sgx-aesm-service/aesm/aesm_service --no-daemon &
  - ./integration-tests/run_multinode.sh

- name: sgx-test
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  privileged: true
  volumes:
  - name: sgx
    path: /dev/sgx
  environment:
    RUST_LOG: debug
  commands:
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export PATH=$CARGO_HOME/bin:$PATH
  - LD_LIBRARY_PATH=/opt/intel/sgx-aesm-service/aesm /opt/intel/sgx-aesm-service/aesm/aesm_service --no-daemon &
  - ./docker/sgx_test.sh

- name: teardown
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - ./integration-tests/cleanup.sh
  when:
    status:
      - success
      - failure

volumes:
  - name: sgx
    host:
      path: /dev/sgx

trigger:
  branch:
  - main
  - staging
  - trying
  event:
  - push

---
kind: pipeline
name: fuzzer

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: cryptocom/fuzzer:latest
  pull: if-not-exists
  environment:
    FUZZIT_API_KEY:
      from_secret: FUZZIT_API_KEY
  commands:
  - ./ci-scripts/fuzzit.sh

trigger:
  branch:
  - main
  event:
  - push
      

---
kind: signature
hmac: af080ab0e7e61803c192a78101706898bbaf548fc6086d5f4d5e105873dbffda

...
